version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
    nodejs: "22"

  jobs:
    build:
      html:
        - uv run jupyter-book build --html

    post_build:
      - mkdir --parents $READTHEDOCS_OUTPUT/html/
      - cp --recursive _build/html/* $READTHEDOCS_OUTPUT/html/

formats: []

python:
  install:
    - method: uv
      path: .
      command: sync --group docs
