# Publish archives to PyPI and TestPyPI using GitHub Actions
name: Publish to PyPI
on: [push, pull_request, workflow_dispatch]
jobs:
  build-artifact:
    name: Build echoregions package
    runs-on: ubuntu-20.04
    if: github.repository == 'OSOceanAcoustics/echoregions'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # fetch all history so that setuptools-scm works
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.9
    - name: Install dependencies
      run: python -m pip install setuptools wheel
    - name: Build source and wheel distributions
      run: |
        python setup.py sdist bdist_wheel
        echo ""
        echo "Generated files:"
        ls -lh dist/
    - uses: actions/upload-artifact@v3
      with:
        name: releases
        path: dist

  test-built-dist:
    name: Test echoregions package
    needs: build-artifact
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-python@v4.7.0
      name: Install Python
      with:
        python-version: 3.9
    - uses: actions/download-artifact@v3
      with:
        name: releases
        path: dist
    - name: List contents of built dist
      run: |
        ls -ltrh
        ls -ltrh dist
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.10
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        verbose: true
    - name: Check pypi packages
      run: |
        sleep 3
        python -m pip install --upgrade pip

        echo "=== Testing wheel file ==="
        # Install wheel to get dependencies and check import
        python -m pip install --extra-index-url https://test.pypi.org/simple --upgrade --pre echoregions
        python -c "import echoregions; print(echoregions.__version__)"
        echo "=== Done testing wheel file ==="

        echo "=== Testing source tar file ==="
        # Install tar gz and check import
        python -m pip uninstall --yes echoregions
        python -m pip install --extra-index-url https://test.pypi.org/simple --upgrade --pre --no-binary=:all: echoregions
        python -c "import echoregions; print(echoregions.__version__)"
        echo "=== Done testing source tar file ==="
